### ISSUE TITLE
Peer review - Week #3 - Repository

### ISSUE THREAD

**Issue by lisaoude** [veerleprins/browser-technologies-2021#5]
### General
- You have added a great description at the top right of your repository, including what you worked with to make your app ✔️🔥 
- Clear commit messages 👏 
- Great folder structure 🔥 

---

### Readme
- Great short description added. It tell me why you made your app and gives an introduction on how you made it! 😄 
- Case is well described 🔥
- Live link is working 🤩🔗 
- Lovely flow added! Makes it very clear what your app will look like!
- Browser technologies section looks good, I'm sure it'll look great once fully filled out ✨
- Installing is described well!
- It might be nice to describe the layers of your application, because you're focussing on progressive enhancement

---

*Nice work, keep it up 🔥*

--- 

## To Fix This Issue

- [x] Write something about the different layers of you application (pleasurable, functional, etc)

**Comment by veerleprins** [comment]
Thanks for the feedback 👍 😄
