### ISSUE TITLE
Peer review - Week #3 - JS code

### ISSUE THREAD

**Issue by lisaoude** [veerleprins/browser-technologies-2021#6]
## Client side
- Looking a little empty so far 👀 

## Server side 
- Server.js is short & very tidy 
- Route files look very clean and are easily understandable 🔥🧹 

---

*Looking cleeeaaan 🧹🔥*

--- 

## To Fix This Issue
- [x] Add client side JS code

**Comment by veerleprins** [comment]
Thanks for the feedback. Indeed I have now added client side code  👍
