### ISSUE TITLE
Peer review - Week #3 - CSS code

### ISSUE THREAD

**Issue by lisaoude** [veerleprins/browser-technologies-2021#8]
## Review
- I don't know in which browsers you're going to test your application in, but @supports isn't supported in all browsers, [which you can see here](https://caniuse.com/?search=%40supports)

## To Fix This Issue
- [x] Look in to support for @supports

**Comment by veerleprins** [comment]
Thanks for the feedback 👍 😄 . I took a quick look at it now!
